routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('clientes', 'ClienteController');
    Route::resource('clienteInfos', 'ClienteInfosController');
    Route::resource('pensions', 'PensionsController');
    Route::resource('imgIngresos', 'ImgIngresosController');
    Route::resource('centralUsers', 'CentralUserController');
    Route::resource('ingresos', 'IngresosController');
    Route::resource('bancoColects', 'BancoColectController');
    Route::resource('empresaColects', 'EmpresaColectController');
    Route::resource('estacionamientos', 'EstacionamientosController');
    Route::resource('tickets', 'ticketController');
    Route::resource('facturas', 'facturasController');
    Route::get('/informe', 'InformeController@index')->name('informe');
    Route::post('/buscar/facturas', 'facturasController@busqueda')->name('busqueda');
    Route::post('/email', 'facturasController@enviarEmail')->name('email');
    Route::post('/emailespecial', 'facturasController@enviarEmailespecial')->name('emailespecial');
    Route::get('/xml/{id}', 'facturasController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'facturasController@downloadPDF')->name('pdf');
    Route::resource('facturaPensions', 'FacturaPensionController');
    Route::resource('detalles', 'DetalleController');
    Route::get('/xmlPen/{id}', 'FacturaPensionController@downloadpenXML')->name('xmlPen');
    Route::get('/pdfPen/{id}', 'FacturaPensionController@downloadpenPdf')->name('pdfPen');
    //pensiones
    Route::get('/contp/{id}', 'DetalleController@downloadContPdf')->name('contp');
    Route::get('/scontp/{id}', 'DetalleController@downloadSContPdf')->name('scontp');
    Route::get('/ccontp/{id}', 'DetalleController@downloadComprobantedomPdf')->name('ccontp');
    Route::get('/ine/{id}', 'DetalleController@downloadIne')->name('ine');
    Route::get('/licencia/{id}', 'DetalleController@downloadLic')->name('licencia');
    Route::get('/tarjetaC/{id}', 'DetalleController@downloadTarC')->name('tarjetaC');
    Route::get('/compPago/{id}', 'DetalleController@downloadcompPago')->name('compPago');
    Route::resource('pagos', 'PagoController');
    Route::post('updatePago', 'PagoController@update');
    Route::get('/compPago/{id}', 'PagoController@downloadcompPago')->name('compPago');
    Route::get('/inactivo/{id}', 'DetalleController@inactivo')->name('inactivo');
    Route::get('/bajatemporal/{id}', 'DetalleController@temporal')->name('bajatemporal');
    Route::resource('reportes', 'ReporteController');
    Route::get('/reportpension', 'ReporteController@reportePen')->name('reportpension');
    Route::get('/pensionesActivas', 'PensionActivaController@index')->name('pensionesActivas');
    Route::resource('actualizacionesPen', 'ActualizaPenController');
    Route::post('/actualizacionesPenDel', 'ActualizaPEnController@destroy')->name('actualizacionesPenDel');
    Route::resource('historicoPen', 'HistoricoController');
    Route::get('/findBusquedaEspecifica/{id}', 'DetalleController@findBusquedaEspecifica')->name('findBusquedaEspecifica');
    //grupocarso
    Route::resource('facturacionespeciales', 'EspecialFacturaController');
    Route::resource('reportesespeciales', 'ReporteEspecialController');
    Route::post('/reportespecial', 'ReporteController@reporteEsp')->name('reportespecial');
});







Route::resource('catBancos', 'catBancoController');


Route::resource('catCfdiUsos', 'CatCfdiUsoController');

Route::resource('metodoPagos', 'MetodoPagoController');

app/Models/FacturaPension.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class FacturaPension
 * @package App\Models
 * @version May 17, 2021, 3:24 am UTC
 *
 * @property \App\Models\CatCfdiUso $idUsocfdi
 * @property \App\Models\CatMetodoPago $idMetodopago
 * @property \App\Models\PensionesDet $idPen
 * @property integer $id_pen
 * @property string $serie
 * @property string $folio
 * @property string|\Carbon\Carbon $fecha_timbrado
 * @property string $uuid
 * @property number $subtotal_factura
 * @property number $iva_factura
 * @property number $total_factura
 * @property string $XML
 * @property string $PDF
 * @property string $estatus
 * @property integer $id_usoCFDI
 * @property integer $id_metodoPago
 */
class FacturaPension extends Model
{
    //use SoftDeletes;

    public $table = 'facturaPensiones';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    //protected $dates = ['deleted_at'];

    public $connection = "mysql2";

    public $fillable = [
        'id_pen',
        'serie',
        'folio',
        'fecha_timbrado',
        'uuid',
        'subtotal_factura',
        'iva_factura',
        'total_factura',
        'XML',
        'PDF',
        'estatus',
        'id_usoCFDI',
        'id_metodoPago'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_pen' => 'integer',
        'serie' => 'string',
        'folio' => 'string',
        'fecha_timbrado' => 'datetime',
        'uuid' => 'string',
        'subtotal_factura' => 'decimal:2',
        'iva_factura' => 'decimal:2',
        'total_factura' => 'decimal:2',
        'XML' => 'string',
        'PDF' => 'string',
        'estatus' => 'string',
        'id_usoCFDI' => 'integer',
        'id_metodoPago' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id_pen' => 'required|integer',
        /*'serie' => 'required|string|max:255',
        'folio' => 'required|string|max:255',*/
        'fecha_timbrado' => 'nullable',
        'uuid' => 'nullable|string|max:255',
        'subtotal_factura' => 'nullable|numeric',
        'iva_factura' => 'nullable|numeric',
        'total_factura' => 'nullable|numeric',
        'XML' => 'nullable|string',
        'PDF' => 'nullable|string',
        'estatus' => 'nullable|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'id_usoCFDI' => 'nullable|integer',
        'id_metodoPago' => 'nullable|integer'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idUsocfdi()
    {
        return $this->belongsTo(\App\Models\CatCfdiUso::class, 'id_usoCFDI');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idMetodopago()
    {
        return $this->belongsTo(\App\Models\CatMetodoPago::class, 'id_metodoPago');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idPen()
    {
        return $this->belongsTo(\App\Models\PensionesDet::class, 'id_pen');
    }
}

app/Http/Controllers/FacturaPensionController.php
<?php

namespace App\Http\Controllers;

use Flash;
use Response;
use App\Models\Detalle;
use App\Models\catBanco;
use App\Models\CatCfdiUso;
use Illuminate\Http\Request;
use App\Models\FacturaPension;
use App\Models\MetodoPago;
use App\Http\Controllers\AppBaseController;
use App\Repositories\FacturaPensionRepository;
use App\Http\Requests\CreateFacturaPensionRequest;
use App\Http\Requests\UpdateFacturaPensionRequest;
use Auth;
use DB;

class FacturaPensionController extends AppBaseController
{
    /** @var  FacturaPensionRepository */
    private $facturaPensionRepository;

    public function __construct(FacturaPensionRepository $facturaPensionRepo)
    {
        $this->facturaPensionRepository = $facturaPensionRepo;
    }

    /**
     * Display a listing of the FacturaPension.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $facturaPensions = $this->facturaPensionRepository->all();

        $pensionActiva = "
        select
        facturaPensiones.id as facturaId,
        facturaPensiones.serie as serie,
        facturaPensiones.folio as folio,
        facturaPensiones.fecha_timbrado as fecha_timbrado,
        pensionesDet.id,
        concat(Clientes.nombres, ' ', Clientes.apellido_paterno, ' ', Clientes.apellido_materno) as nombre_cliente,
        Clientes.rfc as RFC,
        facturaPensiones.subtotal_factura as subtotal_factura,
        facturaPensiones.iva_factura as iva,
        facturaPensiones.total_factura as total_factura,
        facturaPensiones.xml as XML_Factura,
        facturaPensiones.pdf as PDF_factura,
        estacionamientos.nombre_proyecto as proyecto,
        estacionamientos.no_estacionamiento as numero_proyecto
        from facturaPensiones inner join pensionesDet on facturaPensiones.id_pen = pensionesDet.id
        inner join estacionamientos on pensionesDet.id_estacionamiento = estacionamientos.id
        inner join  Clientes on pensionesDet.id_cliente = Clientes.id
        where estacionamientos.no_estacionamiento = 7
        order by fecha_timbrado desc
        ";

        $result1 = DB::connection('mysql2')->SELECT($pensionActiva);
        //dd($result1);

        return view('factura_pensions.index')
            ->with('facturaPensions', $result1);
    }

    /**
     * Show the form for creating a new FacturaPension.
     *
     * @return Response
     */
    public function create()
    {
        $pensiones = Detalle::select('pensionesDet.*', 'Clientes.*')
        ->join('Clientes', 'pensionesDet.id_Cliente', '=', 'Clientes.id')
        ->get();


        $bancos = catBanco::get();
        $usocfdi = catCfdiUso::get();
        $metodo = MetodoPago::get();

        return view('factura_pensions.create')->with('pensiones', $pensiones)->with('bancos', $bancos)
        ->with('usocfdis', $usocfdi)->with('metodos', $metodo);
    }

    /**
     * Store a newly created FacturaPension in storage.
     *
     * @param CreateFacturaPensionRequest $request
     *
     * @return Response
     */
    public function store(CreateFacturaPensionRequest $request)
    {
        $input = $request->all();

        $xml = '';
        $pdf = '';

        $xml = request()->file('XML');
        if ($xml != null) {
            $datacont = $xml->get();
            $nombre_contrato = $xml->getBasename();
            $cont = file_get_contents($xml);
            //$contdata = base64_encode($cont);
            $input['XML'] = $cont;
            //$contrato = $this->pensionRepository->create($input);
        }

        $pdf = request()->file('PDF');
        if ($pdf != null) {
            $datascont = $pdf->get();
            $nombre_scontrato = $pdf->getBasename();
            $scont = file_get_contents($pdf);
            $scontdata = base64_encode($scont);
            $input['PDF'] = $scontdata;
            //$contrato = $this->pensionRepository->create($input);
        }

        $facturaPension = $this->facturaPensionRepository->create($input);

        return redirect(route('facturaPensions.index'));
    }

    /**
     * Display the specified FacturaPension.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $facturaPension = $this->facturaPensionRepository->find($id);

        if (empty($facturaPension)) {
            Flash::error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        return view('factura_pensions.show')->with('facturaPension', $facturaPension);
    }

    /**
     * Show the form for editing the specified FacturaPension.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $facturaPension = $this->facturaPensionRepository->find($id);

        if (empty($facturaPension)) {
            Flash::error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        $pensiones = Detalle::select('pensionesDet.*', 'Clientes.*')
        ->join('Clientes', 'pensionesDet.id', '=', 'Clientes.id_pension')
        ->get();


        $bancos = catBanco::get();
        $usocfdi = catCfdiUso::get();
        $metodo = MetodoPago::get();

        return view('factura_pensions.edit')->with('facturaPension', $facturaPension)->with('pensiones', $pensiones)->with('bancos', $bancos)
        ->with('usocfdis', $usocfdi)->with('metodos', $metodo);
    }

    /**
     * Update the specified FacturaPension in storage.
     *
     * @param int $id
     * @param UpdateFacturaPensionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFacturaPensionRequest $request)
    {
        $facturaPension = $this->facturaPensionRepository->find($id);

        if (empty($facturaPension)) {
            Flash::error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        $facturaPension = $this->facturaPensionRepository->update($request->all(), $id);

        Flash::success('Factura Pension updated successfully.');

        return redirect(route('facturaPensions.index'));
    }

    /**
     * Remove the specified FacturaPension from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $facturaPension = $this->facturaPensionRepository->find($id);

        if (empty($facturaPension)) {
            Flash::error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        $this->facturaPensionRepository->delete($id);

        Flash::success('Factura Pension deleted successfully.');

        return redirect(route('facturaPensions.index'));
    }

    public function downloadpenPdf($id)
    {
        $pdf = FacturaPension::find($id);
        $archivo = $pdf->PDF;
        $decoded = base64_decode($archivo);
        $path = "pdfs/" . $pdf->id . ".pdf";
        file_put_contents($path, $decoded);
        header("Content-disposition: attachment; filename=contrato-fact$pdf->id.pdf");
        header("Content-type: application/pdf");
        readfile($path);
        unlink($path);
    }

    public function downloadpenXML($id)
    {
        //$id = \request()->request;
        //dd($id);
        $xml = FacturaPension::find($id);
        $archivo = $xml->XML;
        $path = "xml_down/" . $xml->id . ".xml";
        //dd($uuid);
        file_put_contents($path, $archivo);
        header("Content-disposition: attachment; filename=fact$xml->id.xml");
        header("Content-type: application/xml");
        readfile($path);
        unlink($path);

        //Flash::success('Factura descargada');

        //return redirect(route('facturas.index'));
    }
}

resources/views/factura_pensions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Solicitar factura pensión</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {!! Form::open(['route' => 'facturaPensions.store', 'enctype' => 'multipart/form-data']) !!}

                @include('factura_pensions.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/factura_pensions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Factura Pension
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($facturaPension, ['route' => ['facturaPensions.update', $facturaPension->id], 'method' => 'patch']) !!}

                        @include('factura_pensions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/factura_pensions/fields.blade.php
<!-- Id Pen Field -->
<div class="form-group col-sm-12">
    {!! Form::label('id_pen', 'Pensión:') !!}
    <select class="browser-default custom-select" name="id_pen" required>
        <option value="" disabled selected>Escoja una opción</option>
        @foreach ($pensiones as $pension)
            <option value="{{ $pension->id }}">{{ $pension->noTarjeta }} / {{ $pension->RFC}} / {{ $pension->nombres }} {{ $pension->apellido_paterno }} {{ $pension->apellido_materno}}</option>
        @endforeach
    </select>
</div>

<!-- Serie Field -->
{{-- <div class="form-group col-sm-12">
    {!! Form::label('serie', 'Serie:') !!}
    {!! Form::text('serie', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div> --}}

<!-- Folio Field -->
{{-- <div class="form-group col-sm-12">
    {!! Form::label('folio', 'Folio:') !!}
    {!! Form::text('folio', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div> --}}

<!-- Fecha Timbrado Field -->
{{--<div class="form-group col-sm-12">
    {!! Form::label('fecha_timbrado', 'Fecha Timbrado:') !!}
    {!! Form::date('fecha_timbrado', null, ['class' => 'form-control', 'id' => 'fecha_timbrado']) !!}
</div> --}}

@push('scripts')
    <script type="text/javascript">
        $('#fecha_timbrado').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: false
        })

    </script>
@endpush

<!-- Uuid Field -->
{{--<div class="form-group col-sm-12">
    {!! Form::label('uuid', 'Uuid:') !!}
    {!! Form::text('uuid', null, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}
</div>--}}

<!-- Subtotal Factura Field -->
{{-- <div class="form-group col-sm-12">
    {!! Form::label('subtotal_factura', 'Subtotal Factura:') !!}
    {!! Form::number('subtotal_factura', null, ['class' => 'form-control']) !!}
</div> --}}

<!-- Iva Factura Field -->
{{--<div class="form-group col-sm-12">
    {!! Form::label('iva_factura', 'Iva Factura:') !!}
    {!! Form::number('iva_factura', null, ['class' => 'form-control']) !!}
</div>--}}

<!-- Total Factura Field -->
<div class="form-group col-sm-12">
    {!! Form::label('total_factura', 'Total Factura:') !!}
    {!! Form::number('total_factura', null, ['class' => 'form-control']) !!}
</div>

<!-- Xml Field -->

{{--<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('XML', 'Xml:') !!}
    <div class="file-field">
        <div class="float-left btn btn-primary btn-sm">
            <span>Cargar xml</span>
            <input type="file" name="XML" id="foto" accept="application/xml">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" name="XML" id="foto" accept="application/xml" type="text"
                placeholder="Cargar xml">
        </div>
    </div>
</div>

<!-- Pdf Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('PDF', 'Pdf:') !!}
    <div class="file-field">
        <div class="float-left btn btn-primary btn-sm">
            <span>Cargar pdf</span>
            <input type="file" name="PDF" id="foto" accept="application/pdf">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" name="PDF" id="foto" accept="application/pdf" type="text"
                placeholder="Cargar pdf">
        </div>
    </div>
</div>--}}

<!-- Estatus Field -->
{!! Form::hidden('estatus', 2, ['class' => 'form-control', 'maxlength' => 255, 'maxlength' => 255]) !!}

<!-- Id Usocfdi Field -->
<div class="form-group col-sm-12">
    {!! Form::label('id_usoCFDI', 'Usocfdi:') !!}
    <select class="browser-default custom-select" name="id_usoCFDI" required>
        <option value="" disabled selected>Escoja una opción</option>
        @foreach ($usocfdis as $uso)
            <option value="{{ $uso->id }}">{{ $uso->claveSat }} / {{ $uso->descricion }}</option>
        @endforeach
    </select>
</div>

<!-- Id Metodopago Field -->
<div class="form-group col-sm-12">
    {!! Form::label('id_metodoPago', 'Metodo de pago:') !!}
    <select class="browser-default custom-select" name="id_metodoPago" required>
        <option value="" disabled selected>Escoja una opción</option>
        @foreach ($metodos as $met)
            <option value="{{ $met->id }}">{{ $met->clave }} / {{ $met->Descripcion }}</option>
        @endforeach
    </select>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enviar', ['class' => 'btn btn-primary', 'onclick' => "return confirm('¿La información es correcta?')"]) !!}
    <a href="{{ route('facturaPensions.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/factura_pensions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <div class="view view-cascade gradient-card-header default-color">
                <h3 class="card-header-title">Facturas activas</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row">
            <div class="col-6">
                <button type="button" class="btn btn-default btn-lg">
                    facturas: <span class="ml-4 counter badge badge-danger"></span>
                </button>
            </div>
            <div class="text-right col-3">
                <a type="button" class="btn btn-dark btn-rounded right-aligned" href="{!! route('facturaPensions.create') !!}">
                    Solicitar factura
                </a>
            </div>
        </div>
        <br>
        @include('factura_pensions.table')
    </section>
@endsection

resources/views/factura_pensions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Factura Pension
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('factura_pensions.show_fields')
                    <a href="{{ route('facturaPensions.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/factura_pensions/show_fields.blade.php
<!-- Id Pen Field -->
<div class="form-group">
    {!! Form::label('id_pen', 'Id Pen:') !!}
    <p>{{ $facturaPension->id_pen }}</p>
</div>

<!-- Serie Field -->
<div class="form-group">
    {!! Form::label('serie', 'Serie:') !!}
    <p>{{ $facturaPension->serie }}</p>
</div>

<!-- Folio Field -->
<div class="form-group">
    {!! Form::label('folio', 'Folio:') !!}
    <p>{{ $facturaPension->folio }}</p>
</div>

<!-- Fecha Timbrado Field -->
<div class="form-group">
    {!! Form::label('fecha_timbrado', 'Fecha Timbrado:') !!}
    <p>{{ $facturaPension->fecha_timbrado }}</p>
</div>

<!-- Uuid Field -->
<div class="form-group">
    {!! Form::label('uuid', 'Uuid:') !!}
    <p>{{ $facturaPension->uuid }}</p>
</div>

<!-- Subtotal Factura Field -->
<div class="form-group">
    {!! Form::label('subtotal_factura', 'Subtotal Factura:') !!}
    <p>{{ $facturaPension->subtotal_factura }}</p>
</div>

<!-- Iva Factura Field -->
<div class="form-group">
    {!! Form::label('iva_factura', 'Iva Factura:') !!}
    <p>{{ $facturaPension->iva_factura }}</p>
</div>

<!-- Total Factura Field -->
<div class="form-group">
    {!! Form::label('total_factura', 'Total Factura:') !!}
    <p>{{ $facturaPension->total_factura }}</p>
</div>

<!-- Xml Field -->
<div class="form-group">
    {!! Form::label('XML', 'Xml:') !!}
    <p>{{ $facturaPension->XML }}</p>
</div>

<!-- Pdf Field -->
<div class="form-group">
    {!! Form::label('PDF', 'Pdf:') !!}
    <p>{{ $facturaPension->PDF }}</p>
</div>

<!-- Estatus Field -->
<div class="form-group">
    {!! Form::label('estatus', 'Estatus:') !!}
    <p>{{ $facturaPension->estatus }}</p>
</div>

<!-- Id Usocfdi Field -->
<div class="form-group">
    {!! Form::label('id_usoCFDI', 'Id Usocfdi:') !!}
    <p>{{ $facturaPension->id_usoCFDI }}</p>
</div>

<!-- Id Metodopago Field -->
<div class="form-group">
    {!! Form::label('id_metodoPago', 'Id Metodopago:') !!}
    <p>{{ $facturaPension->id_metodoPago }}</p>
</div>

resources/views/factura_pensions/table.blade.php
<div class="table-responsive">
    <table id="dtBasicExample" class="table table-striped" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Serie</th>
                <th>Folio</th>
                <th>Fecha Timbrado</th>
                <th>Cliente</th>
                <th>RFC</th>
                <th>SubTotal</th>
                <th>Iva</th>
                <th>Total</th>
                <th>Proyecto</th>
                <th>Xml</th>
                <th>Pdf</th>
                <!--<th>Usocfdi</th>
                <th>Metodo pago</th>-->
                <!-- <th colspan="3">Acción</th> -->
            </tr>
        </thead>
        <tbody>
            @foreach ($facturaPensions as $facturaPension)
                <tr>
                    <td>{{ $facturaPension->facturaId }}</td>
                    <td>
                        @if ($facturaPension->serie)
                            {{ $facturaPension->serie }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->folio)
                            {{ $facturaPension->folio }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->fecha_timbrado)
                            {{ $facturaPension->fecha_timbrado }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->nombre_cliente)
                            {{ $facturaPension->nombre_cliente }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->RFC)
                            {{ $facturaPension->RFC }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->subtotal_factura)
                            {{ $facturaPension->subtotal_factura }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->iva)
                            {{ $facturaPension->iva }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>{{ $facturaPension->total_factura }}</td>
                    <td>
                        @if ($facturaPension->proyecto)
                            {{ $facturaPension->numero_proyecto }} / {{ $facturaPension->proyecto }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                            <a href="{!! route('xmlPen', [$facturaPension->facturaId]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                    class="fas fa-download"></i></a>
                    </td>
                    <td>
                            <a href="{!! route('pdfPen', [$facturaPension->facturaId]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                    class="fas fa-download"></i></a>
                    </td>
                   {{-- <td>
                        {!! Form::open(['route' => ['facturaPensions.destroy', $facturaPension->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                             <a href="{{ route('facturaPensions.show', [$facturaPension->id]) }}"
                                class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                            <a href="{{ route('facturaPensions.edit', [$facturaPension->id]) }}"
                                class='btn btn-default btn-xs'>Editar</a>
                            {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                    </td> --}}
                </tr>
            @endforeach
        </tbody>
    </table>
</div>