routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('clientes', 'ClienteController');
    Route::resource('clienteInfos', 'ClienteInfosController');
    Route::resource('pensions', 'PensionsController');
    Route::resource('imgIngresos', 'ImgIngresosController');
    Route::resource('centralUsers', 'CentralUserController');
    Route::resource('ingresos', 'IngresosController');
    Route::resource('bancoColects', 'BancoColectController');
    Route::resource('empresaColects', 'EmpresaColectController');
    Route::resource('estacionamientos', 'EstacionamientosController');
    Route::resource('tickets', 'ticketController');
    Route::resource('facturas', 'facturasController');
    Route::get('/informe', 'InformeController@index')->name('informe');
    Route::post('/buscar/facturas', 'facturasController@busqueda')->name('busqueda');
    Route::post('/email', 'facturasController@enviarEmail')->name('email');
    Route::post('/emailespecial', 'facturasController@enviarEmailespecial')->name('emailespecial');
    Route::get('/xml/{id}', 'facturasController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'facturasController@downloadPDF')->name('pdf');
    Route::resource('facturaPensions', 'FacturaPensionController');
    Route::resource('detalles', 'DetalleController');
    Route::get('/xmlPen/{id}', 'FacturaPensionController@downloadpenXML')->name('xmlPen');
    Route::get('/pdfPen/{id}', 'FacturaPensionController@downloadpenPdf')->name('pdfPen');
    //pensiones
    Route::get('/contp/{id}', 'DetalleController@downloadContPdf')->name('contp');
    Route::get('/scontp/{id}', 'DetalleController@downloadSContPdf')->name('scontp');
    Route::get('/ccontp/{id}', 'DetalleController@downloadComprobantedomPdf')->name('ccontp');
    Route::get('/ine/{id}', 'DetalleController@downloadIne')->name('ine');
    Route::get('/licencia/{id}', 'DetalleController@downloadLic')->name('licencia');
    Route::get('/tarjetaC/{id}', 'DetalleController@downloadTarC')->name('tarjetaC');
    Route::get('/compPago/{id}', 'DetalleController@downloadcompPago')->name('compPago');
    Route::resource('pagos', 'PagoController');
    Route::post('updatePago', 'PagoController@update');
    Route::get('/compPago/{id}', 'PagoController@downloadcompPago')->name('compPago');
    Route::get('/inactivo/{id}', 'DetalleController@inactivo')->name('inactivo');
    Route::get('/bajatemporal/{id}', 'DetalleController@temporal')->name('bajatemporal');
    Route::resource('reportes', 'ReporteController');
    Route::get('/reportpension', 'ReporteController@reportePen')->name('reportpension');
    Route::get('/pensionesActivas', 'PensionActivaController@index')->name('pensionesActivas');
    Route::resource('actualizacionesPen', 'ActualizaPenController');
    Route::post('/actualizacionesPenDel', 'ActualizaPEnController@destroy')->name('actualizacionesPenDel');
    Route::resource('historicoPen', 'HistoricoController');
    Route::get('/findBusquedaEspecifica/{id}', 'DetalleController@findBusquedaEspecifica')->name('findBusquedaEspecifica');
    //grupocarso
    Route::resource('facturacionespeciales', 'EspecialFacturaController');
    Route::resource('reportesespeciales', 'ReporteEspecialController');
    Route::post('/reportespecial', 'ReporteController@reporteEsp')->name('reportespecial');
});







Route::resource('catBancos', 'catBancoController');


Route::resource('catCfdiUsos', 'CatCfdiUsoController');

Route::resource('metodoPagos', 'MetodoPagoController');

app/Models/CatCfdiUso.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class CatCfdiUso
 * @package App\Models
 * @version June 2, 2021, 9:38 am UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection $facturaPensiones
 * @property string $claveSat
 * @property string $descricion
 */
class CatCfdiUso extends Model
{

    public $table = 'cat_CfdiUso';

    public $connection = "mysql2";

    public $fillable = [
        'claveSat',
        'descricion'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'claveSat' => 'string',
        'descricion' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function facturaPensiones()
    {
        return $this->hasMany(\App\Models\FacturaPensione::class, 'id_usoCFDI');
    }
}

app/Http/Controllers/CatCfdiUsoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCatCfdiUsoRequest;
use App\Http\Requests\UpdateCatCfdiUsoRequest;
use App\Repositories\CatCfdiUsoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CatCfdiUsoController extends AppBaseController
{
    /** @var  CatCfdiUsoRepository */
    private $catCfdiUsoRepository;

    public function __construct(CatCfdiUsoRepository $catCfdiUsoRepo)
    {
        $this->catCfdiUsoRepository = $catCfdiUsoRepo;
    }

    /**
     * Display a listing of the CatCfdiUso.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $catCfdiUsos = $this->catCfdiUsoRepository->all();

        return view('cat_cfdi_usos.index')
            ->with('catCfdiUsos', $catCfdiUsos);
    }

    /**
     * Show the form for creating a new CatCfdiUso.
     *
     * @return Response
     */
    public function create()
    {
        return view('cat_cfdi_usos.create');
    }

    /**
     * Store a newly created CatCfdiUso in storage.
     *
     * @param CreateCatCfdiUsoRequest $request
     *
     * @return Response
     */
    public function store(CreateCatCfdiUsoRequest $request)
    {
        $input = $request->all();

        $catCfdiUso = $this->catCfdiUsoRepository->create($input);

        Flash::success('Cat Cfdi Uso saved successfully.');

        return redirect(route('catCfdiUsos.index'));
    }

    /**
     * Display the specified CatCfdiUso.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $catCfdiUso = $this->catCfdiUsoRepository->find($id);

        if (empty($catCfdiUso)) {
            Flash::error('Cat Cfdi Uso not found');

            return redirect(route('catCfdiUsos.index'));
        }

        return view('cat_cfdi_usos.show')->with('catCfdiUso', $catCfdiUso);
    }

    /**
     * Show the form for editing the specified CatCfdiUso.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $catCfdiUso = $this->catCfdiUsoRepository->find($id);

        if (empty($catCfdiUso)) {
            Flash::error('Cat Cfdi Uso not found');

            return redirect(route('catCfdiUsos.index'));
        }

        return view('cat_cfdi_usos.edit')->with('catCfdiUso', $catCfdiUso);
    }

    /**
     * Update the specified CatCfdiUso in storage.
     *
     * @param int $id
     * @param UpdateCatCfdiUsoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCatCfdiUsoRequest $request)
    {
        $catCfdiUso = $this->catCfdiUsoRepository->find($id);

        if (empty($catCfdiUso)) {
            Flash::error('Cat Cfdi Uso not found');

            return redirect(route('catCfdiUsos.index'));
        }

        $catCfdiUso = $this->catCfdiUsoRepository->update($request->all(), $id);

        Flash::success('Cat Cfdi Uso updated successfully.');

        return redirect(route('catCfdiUsos.index'));
    }

    /**
     * Remove the specified CatCfdiUso from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $catCfdiUso = $this->catCfdiUsoRepository->find($id);

        if (empty($catCfdiUso)) {
            Flash::error('Cat Cfdi Uso not found');

            return redirect(route('catCfdiUsos.index'));
        }

        $this->catCfdiUsoRepository->delete($id);

        Flash::success('Cat Cfdi Uso deleted successfully.');

        return redirect(route('catCfdiUsos.index'));
    }
}

resources/views/cat_cfdi_usos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cat Cfdi Uso
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'catCfdiUsos.store']) !!}

                        @include('cat_cfdi_usos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cat_cfdi_usos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cat Cfdi Uso
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($catCfdiUso, ['route' => ['catCfdiUsos.update', $catCfdiUso->id], 'method' => 'patch']) !!}

                        @include('cat_cfdi_usos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/cat_cfdi_usos/fields.blade.php
<!-- Clavesat Field -->
<div class="form-group col-sm-6">
    {!! Form::label('claveSat', 'Clavesat:') !!}
    {!! Form::text('claveSat', null, ['class' => 'form-control','maxlength' => 10,'maxlength' => 10]) !!}
</div>

<!-- Descricion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('descricion', 'Descricion:') !!}
    {!! Form::text('descricion', null, ['class' => 'form-control','maxlength' => 30,'maxlength' => 30]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('catCfdiUsos.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/cat_cfdi_usos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Cat Cfdi Usos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('catCfdiUsos.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('cat_cfdi_usos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/cat_cfdi_usos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cat Cfdi Uso
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('cat_cfdi_usos.show_fields')
                    <a href="{{ route('catCfdiUsos.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cat_cfdi_usos/show_fields.blade.php
<!-- Clavesat Field -->
<div class="form-group">
    {!! Form::label('claveSat', 'Clavesat:') !!}
    <p>{{ $catCfdiUso->claveSat }}</p>
</div>

<!-- Descricion Field -->
<div class="form-group">
    {!! Form::label('descricion', 'Descricion:') !!}
    <p>{{ $catCfdiUso->descricion }}</p>
</div>

resources/views/cat_cfdi_usos/table.blade.php
<div class="table-responsive">
    <table class="table" id="catCfdiUsos-table">
        <thead>
            <tr>
                <th>Clavesat</th>
        <th>Descricion</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($catCfdiUsos as $catCfdiUso)
            <tr>
                <td>{{ $catCfdiUso->claveSat }}</td>
            <td>{{ $catCfdiUso->descricion }}</td>
                <td>
                    {!! Form::open(['route' => ['catCfdiUsos.destroy', $catCfdiUso->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('catCfdiUsos.show', [$catCfdiUso->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('catCfdiUsos.edit', [$catCfdiUso->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>