routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('clientes', 'ClienteController');
    Route::resource('clienteInfos', 'ClienteInfosController');
    Route::resource('pensions', 'PensionsController');
    Route::resource('imgIngresos', 'ImgIngresosController');
    Route::resource('centralUsers', 'CentralUserController');
    Route::resource('ingresos', 'IngresosController');
    Route::resource('bancoColects', 'BancoColectController');
    Route::resource('empresaColects', 'EmpresaColectController');
    Route::resource('estacionamientos', 'EstacionamientosController');
    Route::resource('tickets', 'ticketController');
    Route::resource('facturas', 'facturasController');
    Route::get('/informe', 'InformeController@index')->name('informe');
    Route::post('/buscar/facturas', 'facturasController@busqueda')->name('busqueda');
    Route::post('/email', 'facturasController@enviarEmail')->name('email');
    Route::post('/emailespecial', 'facturasController@enviarEmailespecial')->name('emailespecial');
    Route::get('/xml/{id}', 'facturasController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'facturasController@downloadPDF')->name('pdf');
    Route::resource('facturaPensions', 'FacturaPensionController');
    Route::resource('detalles', 'DetalleController');
    Route::get('/xmlPen/{id}', 'FacturaPensionController@downloadpenXML')->name('xmlPen');
    Route::get('/pdfPen/{id}', 'FacturaPensionController@downloadpenPdf')->name('pdfPen');
    //pensiones
    Route::get('/contp/{id}', 'DetalleController@downloadContPdf')->name('contp');
    Route::get('/scontp/{id}', 'DetalleController@downloadSContPdf')->name('scontp');
    Route::get('/ccontp/{id}', 'DetalleController@downloadComprobantedomPdf')->name('ccontp');
    Route::get('/ine/{id}', 'DetalleController@downloadIne')->name('ine');
    Route::get('/licencia/{id}', 'DetalleController@downloadLic')->name('licencia');
    Route::get('/tarjetaC/{id}', 'DetalleController@downloadTarC')->name('tarjetaC');
    Route::get('/compPago/{id}', 'DetalleController@downloadcompPago')->name('compPago');
    Route::resource('pagos', 'PagoController');
    Route::post('updatePago', 'PagoController@update');
    Route::get('/compPago/{id}', 'PagoController@downloadcompPago')->name('compPago');
    Route::get('/inactivo/{id}', 'DetalleController@inactivo')->name('inactivo');
    Route::get('/bajatemporal/{id}', 'DetalleController@temporal')->name('bajatemporal');
    Route::resource('reportes', 'ReporteController');
    Route::get('/reportpension', 'ReporteController@reportePen')->name('reportpension');
    Route::get('/pensionesActivas', 'PensionActivaController@index')->name('pensionesActivas');
    Route::resource('actualizacionesPen', 'ActualizaPenController');
    Route::post('/actualizacionesPenDel', 'ActualizaPEnController@destroy')->name('actualizacionesPenDel');
    Route::resource('historicoPen', 'HistoricoController');
    Route::get('/findBusquedaEspecifica/{id}', 'DetalleController@findBusquedaEspecifica')->name('findBusquedaEspecifica');
    //grupocarso
    Route::resource('facturacionespeciales', 'EspecialFacturaController');
    Route::resource('reportesespeciales', 'ReporteEspecialController');
    Route::post('/reportespecial', 'ReporteController@reporteEsp')->name('reportespecial');
});







Route::resource('catBancos', 'catBancoController');


Route::resource('catCfdiUsos', 'CatCfdiUsoController');

Route::resource('metodoPagos', 'MetodoPagoController');

app/Models/historico.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class historico extends Model
{
    use HasFactory;
}

app/Http/Controllers/HistoricoController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Carbon\Carbon;
use App\Models\historico;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HistoricoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id_est = Auth::user()->id_est;
        $date = Carbon::now();
        $hoy = $date->format('Y-m-d');

        $pensionActiva = "
        select dis.clave_distrito as distrito,
        dis.nombre as distrital,
        grt.name as gerente,
        grt.email as \"correogerente\",
        est.no_estacionamiento as \"NumeroProyecto\",
        est.nombre_proyecto as \"Proyecto\",
        pd.id as \"NumeroPension\",
        concat(cl.nombres, \" \", cl.apellido_paterno, \" \", cl.apellido_materno) as \"nombrepensionado\",
        'Inactiva' as \"Estado\",
        pd.fechaInactivacion as \"fechabajacancelacion\",
        if(pd.contrato is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoContrato\",
        if(pd.solicitudContrato is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoSolicitud\",
        if(pd.comprobanteDomicilio is null,  \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"ComprobanteDomicilio\",
        if(pd.ine is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoINE\",
        if(pd.licencia is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoLicencia\",
        if(pd.rfc is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoRFC\",
        if(pd.tarjetaCirculacion is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoTarjetaCirculacion\"
        from pensionesDet pd inner join estacionamientos est on est.id = pd.id_estacionamiento
        inner join gerentes grt on  est.id_gerentes = grt.id inner join Clientes cl on
        pd.id_cliente = cl.id inner join distritales dis on dis.id = grt.id_distritales
        where  est.id = 8 #id de estacionamiento a consultar
        and pd.status = 0 #cambiar a 0 cuando inactivas
        and pd.fechaInactivacion is not null
        and date_format(pd.created_at, '%Y-%m-%d') between '2020-01-01' and '$hoy'
        UNION
        #Reporte de pensiones canceladas por ESTACIONAMIENTO
        select dis.clave_distrito as distrito,
        dis.nombre as distrital,
        grt.name as gerente,
        grt.email as \"correogerente\",
        est.no_estacionamiento as \"NumeroProyecto\",
        est.nombre_proyecto as \"Proyecto\",
        pd.id as \"NumeroPension\",
        concat(cl.nombres, \" \", cl.apellido_paterno, \" \", cl.apellido_materno) as \"nombrepensionado\",
        'Cancelada' as \"Estado\",
        pd.fechaCancelacion as \"fechabajacancelacion\",
        if(pd.contrato is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoContrato\",
        if(pd.solicitudContrato is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoSolicitud\",
        if(pd.comprobanteDomicilio is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"ComprobanteDomicilio\",
        if(pd.ine is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoINE\",
        if(pd.licencia is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoLicencia\",
        if(pd.rfc is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoRFC\",
        if(pd.tarjetaCirculacion is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoTarjetaCirculacion\"
        from pensionesDet pd inner join estacionamientos est on est.id = pd.id_estacionamiento
        inner join gerentes grt on  est.id_gerentes = grt.id inner join Clientes cl on
        pd.id_cliente = cl.id inner join distritales dis on dis.id = grt.id_distritales
        where  est.id = 8  #id de estacionamiento a consultar
        and pd.status = 0 #cambiar a 0 cuando inactivas
        and fechaCancelacion is not null
        and date_format(pd.created_at, '%Y-%m-%d')  between '2020-01-01' and '$hoy'
        union
        #Reporte de pensiones activas por estacionamiento
        select dis.clave_distrito as distrito,
        dis.nombre as distrital,
        grt.name as gerente,
        grt.email as \"correogerente\",
        est.no_estacionamiento as \"NumeroProyecto\",
        est.nombre_proyecto as \"Proyecto\",
        pd.id as \"NumeroPension\",
        concat(cl.nombres, \" \", cl.apellido_paterno, \" \", cl.apellido_materno) as \"nombrepensionado\",
        if( cl.estatus = 1 && (date_format(pd.created_at, '%Y-%m')) = (date_format(now(), '%Y-%m')), \"Nueva\", \"Activa\") as \"estado\",
        pd.fechaCancelacion as \"fechabajacancelacion\",
        if(pd.contrato is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoContrato\",
        if(pd.solicitudContrato is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoSolicitud\",
        if(pd.comprobanteDomicilio is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"ComprobanteDomicilio\",
        if(pd.ine is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoINE\",
        if(pd.licencia is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoLicencia\",
        if(pd.rfc is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoRFC\",
        if(pd.tarjetaCirculacion is null, \"No Tiene Documento Asociado\", \"Tiene Documento Asociado\") as \"DocumentoTarjetaCirculacion\"
        from pensionesDet pd inner join estacionamientos est on est.id = pd.id_estacionamiento
        inner join gerentes grt on  est.id_gerentes = grt.id inner join Clientes cl on
        pd.id_cliente = cl.id  inner join distritales dis on dis.id = grt.id_distritales
        where  est.id = 2 #id de estacionamiento a consultar
        and pd.status = 1 #estatus de pensión al momento de la consulta
        and fechaCancelacion is null and pd.fechaInactivacion is null
        and date_format(pd.created_at, '%Y-%m-%d') between '2020-01-01' and '$hoy'
        ";

        $result1 = DB::connection('mysql2')->SELECT($pensionActiva);
        //dd($result1);

        return view('historico.index')->with('detalles', $result1);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\historico  $historico
     * @return \Illuminate\Http\Response
     */
    public function show(historico $historico)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\historico  $historico
     * @return \Illuminate\Http\Response
     */
    public function edit(historico $historico)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\historico  $historico
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, historico $historico)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\historico  $historico
     * @return \Illuminate\Http\Response
     */
    public function destroy(historico $historico)
    {
        //
    }
}

resources/views/historico/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <div class="view view-cascade gradient-card-header default-color">
                <h3 class="card-header-title">Total de pensiones al
                    {{ date('d/M/Y') }}</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row">
            <div class="col-6">
                <button type="button" class="btn btn-default btn-lg">
                    Pensiones: <span class="ml-4 counter badge badge-danger"></span>
                </button>
            </div>
        </div>
        <br>
        @include('historico.table')
        <br>
    </section>
@endsection

resources/views/historico/table.blade.php
<div class="table-responsive">
    <table id="dtBasicExample" class="table">
        <thead>
            <tr>
                <th>Distrito</th>
                <th>Distrital</th>
                <th>Gerente</th>
                <th>Correo gerente</th>
                <th>Numero proyecto</th>
                <th>Proyecto</th>
                <th>Numero pensión</th>
                <th>Nombre pensionado</th>
                <th>Estado</th>
                <th>Fecha baja o cancelación</th>
                <th>Documento contrato</th>
                <th>Documento solicitud</th>
                <th>Comprobante Domicilio</th>
                <th>Documento INE</th>
                <th>Documento Licencia</th>
                <th>Documento RFC</th>
                <th>Documento Tarjeta Circulación</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($detalles as $detalle)
                <tr>
                    <td>{{ $detalle->distrito }}</td>
                    <td>{{ $detalle->distrital }}</td>
                    <td>{{ $detalle->gerente }}</td>
                    <td>{{ $detalle->correogerente }}</td>
                    <td>{{ $detalle->NumeroProyecto }}</td>
                    <td>{{ $detalle->Proyecto }}</td>
                    <td>{{ $detalle->NumeroPension }}</td>
                    <td>{{ $detalle->nombrepensionado }}</td>
                    <td>{{ $detalle->Estado }}</td>
                    <td>{{ $detalle->fechabajacancelacion }}</td>
                    <td>{{ $detalle->DocumentoContrato }}</td>
                    <td>{{ $detalle->DocumentoSolicitud }}</td>
                    <td>{{ $detalle->ComprobanteDomicilio }}</td>
                    <td>{{ $detalle->DocumentoINE }}</td>
                    <td>{{ $detalle->DocumentoLicencia }}</td>
                    <td>{{ $detalle->DocumentoRFC }}</td>
                    <td>{{ $detalle->DocumentoTarjetaCirculacion }}</td>
                    <!-- Datos de bajas en pensiones -->
                    {{-- <td>{{ $detalle->montoPension }}}}<td>
                    <td>{{ $detalle->tipoPension }}}}<td>
                    <td>
                        <a href="{!! route('contp', [$detalle->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                class="fas fa-download"></i></a>
                    </td>
                    <td>

                        <a href="{!! route('scontp', [$detalle->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                class="fas fa-download"></i></a>

                    </td>
                    <td>

                        <a href="{!! route('ccontp', [$detalle->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                class="fas fa-download"></i></a>

                    </td>
                    <td>

                        <a href="{!! route('ine', [$detalle->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                class="fas fa-download"></i></a>

                    </td>
                    <td>

                        <a href="{!! route('licencia', [$detalle->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                class="fas fa-download"></i></a>

                    </td>
                    <td>{{ $detalle->rfc }}</td>
                    <td>

                        <a href="{!! route('tarjetaC', [$detalle->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                class="fas fa-download"></i></a>

                    </td>
                    <td>{{ $detalle->noTarjeta }}</td>
                    <td>
                        @php
                            $fechaAntigua = DB::connection('mysql2')
                                ->table('pensionesDet')
                                ->select('created_at')
                                ->where('id', '=', $detalle->id)
                                ->get();

                            $dbDate = new DateTime($fechaAntigua[0]->created_at);
                            $hoyDate = new DateTime(date('Y-m-d H:i:s'));
                            $timePassed = $dbDate->diff($hoyDate);
                        @endphp
                        @if ($timePassed->days >= 31)
                            Pensión nueva
                        @else
                            @if ($detalle->status == 1)
                                Activo
                            @elseif ($detalle->status == 0)
                                Inactivo
                            @else
                                Baja temporal
                            @endif
                        @endif
                    </td>
                    <td>{{ $detalle->fecha_limite }}</td>
                    <td>
                        <a href="{!! route('inactivo', [$detalle->id]) !!}" class='btn btn-sm btn-red'>Baja</a>
                    </td>
                    <td>
                        <a href="{!! route('bajatemporal', [$detalle->id]) !!}" class='btn btn-sm btn-default'>Baja Temportal</a>
                    </td>
                    {{-- <td>
                        {!! Form::open(['route' => ['detalles.destroy', $detalle->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <!--<a href="{{ route('detalles.show', [$detalle->id]) }}" class='btn btn-default btn-xs'><i
                                    class="glyphicon glyphicon-eye-open"></i></a>-->
                            <a href="{{ route('detalles.edit', [$detalle->id]) }}" class='btn btn-default btn-xs'>Editar</a>
                            {!! Form::button('ELIMINAR', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                    </td> --}}
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
<br>

@section('datatable')

@endsection